# Generated by Django 5.1 on 2024-11-19 21:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('tarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.CharField(max_length=100)),
                ('pax', models.PositiveIntegerField()),
                ('fono', models.CharField(max_length=15)),
                ('garantia', models.CharField(max_length=4)),
                ('fecha_entrada', models.DateField(default=datetime.date.today)),
                ('fecha_salida', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('R', 'Reservado'), ('I', 'Ingresado')], default='R', max_length=1)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('tipoHab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservaApp.tipohab')),
            ],
        ),
    ]
