# Generated by Django 5.1 on 2024-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tipohab',
            name='tarifa',
            field=models.IntegerField(),
        ),
    ]
